// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"GoatChat/GoatChat/internal/chat/domain"
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockChatRepository creates a new instance of MockChatRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockChatRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockChatRepository {
	mock := &MockChatRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockChatRepository is an autogenerated mock type for the ChatRepository type
type MockChatRepository struct {
	mock.Mock
}

type MockChatRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockChatRepository) EXPECT() *MockChatRepository_Expecter {
	return &MockChatRepository_Expecter{mock: &_m.Mock}
}

// SaveChatroom provides a mock function for the type MockChatRepository
func (_mock *MockChatRepository) SaveChatroom(ctx context.Context, cr domain.ChatRoom) error {
	ret := _mock.Called(ctx, cr)

	if len(ret) == 0 {
		panic("no return value specified for SaveChatroom")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ChatRoom) error); ok {
		r0 = returnFunc(ctx, cr)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockChatRepository_SaveChatroom_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveChatroom'
type MockChatRepository_SaveChatroom_Call struct {
	*mock.Call
}

// SaveChatroom is a helper method to define mock.On call
//   - ctx context.Context
//   - cr domain.ChatRoom
func (_e *MockChatRepository_Expecter) SaveChatroom(ctx any, cr any) *MockChatRepository_SaveChatroom_Call {
	return &MockChatRepository_SaveChatroom_Call{Call: _e.mock.On("SaveChatroom", ctx, cr)}
}

func (_c *MockChatRepository_SaveChatroom_Call) Run(run func(ctx context.Context, cr domain.ChatRoom)) *MockChatRepository_SaveChatroom_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.ChatRoom
		if args[1] != nil {
			arg1 = args[1].(domain.ChatRoom)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockChatRepository_SaveChatroom_Call) Return(err error) *MockChatRepository_SaveChatroom_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockChatRepository_SaveChatroom_Call) RunAndReturn(run func(ctx context.Context, cr domain.ChatRoom) error) *MockChatRepository_SaveChatroom_Call {
	_c.Call.Return(run)
	return _c
}
