// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"GoatChat/GoatChat/internal/identity/application/port"

	mock "github.com/stretchr/testify/mock"
)

// NewMockAccessTokenManager creates a new instance of MockAccessTokenManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAccessTokenManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAccessTokenManager {
	mock := &MockAccessTokenManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAccessTokenManager is an autogenerated mock type for the AccessTokenManager type
type MockAccessTokenManager struct {
	mock.Mock
}

type MockAccessTokenManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAccessTokenManager) EXPECT() *MockAccessTokenManager_Expecter {
	return &MockAccessTokenManager_Expecter{mock: &_m.Mock}
}

// Issue provides a mock function for the type MockAccessTokenManager
func (_mock *MockAccessTokenManager) Issue(userID string, sessionID string) (string, error) {
	ret := _mock.Called(userID, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for Issue")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string) (string, error)); ok {
		return returnFunc(userID, sessionID)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = returnFunc(userID, sessionID)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = returnFunc(userID, sessionID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAccessTokenManager_Issue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Issue'
type MockAccessTokenManager_Issue_Call struct {
	*mock.Call
}

// Issue is a helper method to define mock.On call
//   - userID string
//   - sessionID string
func (_e *MockAccessTokenManager_Expecter) Issue(userID any, sessionID any) *MockAccessTokenManager_Issue_Call {
	return &MockAccessTokenManager_Issue_Call{Call: _e.mock.On("Issue", userID, sessionID)}
}

func (_c *MockAccessTokenManager_Issue_Call) Run(run func(userID string, sessionID string)) *MockAccessTokenManager_Issue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAccessTokenManager_Issue_Call) Return(s string, err error) *MockAccessTokenManager_Issue_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockAccessTokenManager_Issue_Call) RunAndReturn(run func(userID string, sessionID string) (string, error)) *MockAccessTokenManager_Issue_Call {
	_c.Call.Return(run)
	return _c
}

// Verify provides a mock function for the type MockAccessTokenManager
func (_mock *MockAccessTokenManager) Verify(rawToken string) (port.AccessTokenClaims, error) {
	ret := _mock.Called(rawToken)

	if len(ret) == 0 {
		panic("no return value specified for Verify")
	}

	var r0 port.AccessTokenClaims
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (port.AccessTokenClaims, error)); ok {
		return returnFunc(rawToken)
	}
	if returnFunc, ok := ret.Get(0).(func(string) port.AccessTokenClaims); ok {
		r0 = returnFunc(rawToken)
	} else {
		r0 = ret.Get(0).(port.AccessTokenClaims)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(rawToken)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAccessTokenManager_Verify_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Verify'
type MockAccessTokenManager_Verify_Call struct {
	*mock.Call
}

// Verify is a helper method to define mock.On call
//   - rawToken string
func (_e *MockAccessTokenManager_Expecter) Verify(rawToken any) *MockAccessTokenManager_Verify_Call {
	return &MockAccessTokenManager_Verify_Call{Call: _e.mock.On("Verify", rawToken)}
}

func (_c *MockAccessTokenManager_Verify_Call) Run(run func(rawToken string)) *MockAccessTokenManager_Verify_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAccessTokenManager_Verify_Call) Return(accessTokenClaims port.AccessTokenClaims, err error) *MockAccessTokenManager_Verify_Call {
	_c.Call.Return(accessTokenClaims, err)
	return _c
}

func (_c *MockAccessTokenManager_Verify_Call) RunAndReturn(run func(rawToken string) (port.AccessTokenClaims, error)) *MockAccessTokenManager_Verify_Call {
	_c.Call.Return(run)
	return _c
}
