// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"GoatChat/GoatChat/internal/identity/domain"
	"context"
	"time"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSessionRepository creates a new instance of MockSessionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSessionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSessionRepository {
	mock := &MockSessionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSessionRepository is an autogenerated mock type for the SessionRepository type
type MockSessionRepository struct {
	mock.Mock
}

type MockSessionRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSessionRepository) EXPECT() *MockSessionRepository_Expecter {
	return &MockSessionRepository_Expecter{mock: &_m.Mock}
}

// ExistsByUserID provides a mock function for the type MockSessionRepository
func (_mock *MockSessionRepository) ExistsByUserID(ctx context.Context, userID uuid.UUID) (bool, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ExistsByUserID")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (bool, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) bool); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSessionRepository_ExistsByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExistsByUserID'
type MockSessionRepository_ExistsByUserID_Call struct {
	*mock.Call
}

// ExistsByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockSessionRepository_Expecter) ExistsByUserID(ctx any, userID any) *MockSessionRepository_ExistsByUserID_Call {
	return &MockSessionRepository_ExistsByUserID_Call{Call: _e.mock.On("ExistsByUserID", ctx, userID)}
}

func (_c *MockSessionRepository_ExistsByUserID_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockSessionRepository_ExistsByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSessionRepository_ExistsByUserID_Call) Return(b bool, err error) *MockSessionRepository_ExistsByUserID_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockSessionRepository_ExistsByUserID_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) (bool, error)) *MockSessionRepository_ExistsByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByRefreshTokenHash provides a mock function for the type MockSessionRepository
func (_mock *MockSessionRepository) FindByRefreshTokenHash(ctx context.Context, rtHash domain.RefreshTokenHash) (*domain.Session, error) {
	ret := _mock.Called(ctx, rtHash)

	if len(ret) == 0 {
		panic("no return value specified for FindByRefreshTokenHash")
	}

	var r0 *domain.Session
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.RefreshTokenHash) (*domain.Session, error)); ok {
		return returnFunc(ctx, rtHash)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.RefreshTokenHash) *domain.Session); ok {
		r0 = returnFunc(ctx, rtHash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Session)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.RefreshTokenHash) error); ok {
		r1 = returnFunc(ctx, rtHash)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSessionRepository_FindByRefreshTokenHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByRefreshTokenHash'
type MockSessionRepository_FindByRefreshTokenHash_Call struct {
	*mock.Call
}

// FindByRefreshTokenHash is a helper method to define mock.On call
//   - ctx context.Context
//   - rtHash domain.RefreshTokenHash
func (_e *MockSessionRepository_Expecter) FindByRefreshTokenHash(ctx any, rtHash any) *MockSessionRepository_FindByRefreshTokenHash_Call {
	return &MockSessionRepository_FindByRefreshTokenHash_Call{Call: _e.mock.On("FindByRefreshTokenHash", ctx, rtHash)}
}

func (_c *MockSessionRepository_FindByRefreshTokenHash_Call) Run(run func(ctx context.Context, rtHash domain.RefreshTokenHash)) *MockSessionRepository_FindByRefreshTokenHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.RefreshTokenHash
		if args[1] != nil {
			arg1 = args[1].(domain.RefreshTokenHash)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSessionRepository_FindByRefreshTokenHash_Call) Return(session *domain.Session, err error) *MockSessionRepository_FindByRefreshTokenHash_Call {
	_c.Call.Return(session, err)
	return _c
}

func (_c *MockSessionRepository_FindByRefreshTokenHash_Call) RunAndReturn(run func(ctx context.Context, rtHash domain.RefreshTokenHash) (*domain.Session, error)) *MockSessionRepository_FindByRefreshTokenHash_Call {
	_c.Call.Return(run)
	return _c
}

// FindByRefreshTokenHashForUpdate provides a mock function for the type MockSessionRepository
func (_mock *MockSessionRepository) FindByRefreshTokenHashForUpdate(ctx context.Context, rtHash domain.RefreshTokenHash) (*domain.Session, error) {
	ret := _mock.Called(ctx, rtHash)

	if len(ret) == 0 {
		panic("no return value specified for FindByRefreshTokenHashForUpdate")
	}

	var r0 *domain.Session
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.RefreshTokenHash) (*domain.Session, error)); ok {
		return returnFunc(ctx, rtHash)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.RefreshTokenHash) *domain.Session); ok {
		r0 = returnFunc(ctx, rtHash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Session)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.RefreshTokenHash) error); ok {
		r1 = returnFunc(ctx, rtHash)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSessionRepository_FindByRefreshTokenHashForUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByRefreshTokenHashForUpdate'
type MockSessionRepository_FindByRefreshTokenHashForUpdate_Call struct {
	*mock.Call
}

// FindByRefreshTokenHashForUpdate is a helper method to define mock.On call
//   - ctx context.Context
//   - rtHash domain.RefreshTokenHash
func (_e *MockSessionRepository_Expecter) FindByRefreshTokenHashForUpdate(ctx any, rtHash any) *MockSessionRepository_FindByRefreshTokenHashForUpdate_Call {
	return &MockSessionRepository_FindByRefreshTokenHashForUpdate_Call{Call: _e.mock.On("FindByRefreshTokenHashForUpdate", ctx, rtHash)}
}

func (_c *MockSessionRepository_FindByRefreshTokenHashForUpdate_Call) Run(run func(ctx context.Context, rtHash domain.RefreshTokenHash)) *MockSessionRepository_FindByRefreshTokenHashForUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.RefreshTokenHash
		if args[1] != nil {
			arg1 = args[1].(domain.RefreshTokenHash)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSessionRepository_FindByRefreshTokenHashForUpdate_Call) Return(session *domain.Session, err error) *MockSessionRepository_FindByRefreshTokenHashForUpdate_Call {
	_c.Call.Return(session, err)
	return _c
}

func (_c *MockSessionRepository_FindByRefreshTokenHashForUpdate_Call) RunAndReturn(run func(ctx context.Context, rtHash domain.RefreshTokenHash) (*domain.Session, error)) *MockSessionRepository_FindByRefreshTokenHashForUpdate_Call {
	_c.Call.Return(run)
	return _c
}

// Revoke provides a mock function for the type MockSessionRepository
func (_mock *MockSessionRepository) Revoke(ctx context.Context, sessionID uuid.UUID, revokedAt time.Time) error {
	ret := _mock.Called(ctx, sessionID, revokedAt)

	if len(ret) == 0 {
		panic("no return value specified for Revoke")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time) error); ok {
		r0 = returnFunc(ctx, sessionID, revokedAt)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSessionRepository_Revoke_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Revoke'
type MockSessionRepository_Revoke_Call struct {
	*mock.Call
}

// Revoke is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID uuid.UUID
//   - revokedAt time.Time
func (_e *MockSessionRepository_Expecter) Revoke(ctx any, sessionID any, revokedAt any) *MockSessionRepository_Revoke_Call {
	return &MockSessionRepository_Revoke_Call{Call: _e.mock.On("Revoke", ctx, sessionID, revokedAt)}
}

func (_c *MockSessionRepository_Revoke_Call) Run(run func(ctx context.Context, sessionID uuid.UUID, revokedAt time.Time)) *MockSessionRepository_Revoke_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSessionRepository_Revoke_Call) Return(err error) *MockSessionRepository_Revoke_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSessionRepository_Revoke_Call) RunAndReturn(run func(ctx context.Context, sessionID uuid.UUID, revokedAt time.Time) error) *MockSessionRepository_Revoke_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockSessionRepository
func (_mock *MockSessionRepository) Save(ctx context.Context, user domain.Session) error {
	ret := _mock.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Session) error); ok {
		r0 = returnFunc(ctx, user)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSessionRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockSessionRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - user domain.Session
func (_e *MockSessionRepository_Expecter) Save(ctx any, user any) *MockSessionRepository_Save_Call {
	return &MockSessionRepository_Save_Call{Call: _e.mock.On("Save", ctx, user)}
}

func (_c *MockSessionRepository_Save_Call) Run(run func(ctx context.Context, user domain.Session)) *MockSessionRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Session
		if args[1] != nil {
			arg1 = args[1].(domain.Session)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSessionRepository_Save_Call) Return(err error) *MockSessionRepository_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSessionRepository_Save_Call) RunAndReturn(run func(ctx context.Context, user domain.Session) error) *MockSessionRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateRefreshTokenHash provides a mock function for the type MockSessionRepository
func (_mock *MockSessionRepository) UpdateRefreshTokenHash(ctx context.Context, sessionID uuid.UUID, newRTHash domain.RefreshTokenHash) error {
	ret := _mock.Called(ctx, sessionID, newRTHash)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRefreshTokenHash")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, domain.RefreshTokenHash) error); ok {
		r0 = returnFunc(ctx, sessionID, newRTHash)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSessionRepository_UpdateRefreshTokenHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateRefreshTokenHash'
type MockSessionRepository_UpdateRefreshTokenHash_Call struct {
	*mock.Call
}

// UpdateRefreshTokenHash is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID uuid.UUID
//   - newRTHash domain.RefreshTokenHash
func (_e *MockSessionRepository_Expecter) UpdateRefreshTokenHash(ctx any, sessionID any, newRTHash any) *MockSessionRepository_UpdateRefreshTokenHash_Call {
	return &MockSessionRepository_UpdateRefreshTokenHash_Call{Call: _e.mock.On("UpdateRefreshTokenHash", ctx, sessionID, newRTHash)}
}

func (_c *MockSessionRepository_UpdateRefreshTokenHash_Call) Run(run func(ctx context.Context, sessionID uuid.UUID, newRTHash domain.RefreshTokenHash)) *MockSessionRepository_UpdateRefreshTokenHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 domain.RefreshTokenHash
		if args[2] != nil {
			arg2 = args[2].(domain.RefreshTokenHash)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSessionRepository_UpdateRefreshTokenHash_Call) Return(err error) *MockSessionRepository_UpdateRefreshTokenHash_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSessionRepository_UpdateRefreshTokenHash_Call) RunAndReturn(run func(ctx context.Context, sessionID uuid.UUID, newRTHash domain.RefreshTokenHash) error) *MockSessionRepository_UpdateRefreshTokenHash_Call {
	_c.Call.Return(run)
	return _c
}
