template: testify

packages:
  GoatChat/GoatChat/internal/chat/application/port:
    config:
      dir: internal/chat/application/port/mocks
      filename: "chat_repository_mock.go"
      pkgname: mocks
      structname: "Mock{{.InterfaceName}}"
    interfaces:
      ChatRepository:
  GoatChat/GoatChat/internal/identity/application/port:
    config:
      all: true
      dir: internal/identity/application/port/mocks
      filename: "{{.InterfaceName | snakecase}}_mock.go"
      pkgname: mocks
      structname: "Mock{{.InterfaceName}}"
    interfaces:
      UserRepository:
  GoatChat/GoatChat/internal/shared/db_tx:
    config:
      dir: internal/shared/db_tx/testutils
      filename: "tx_mock.go"
      pkgname: testutils
      structname: "Mock{{.InterfaceName}}"
    interfaces:
      Tx:
