// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package testutils

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockTx creates a new instance of MockTx. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTx(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTx {
	mock := &MockTx{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTx is an autogenerated mock type for the Tx type
type MockTx struct {
	mock.Mock
}

type MockTx_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTx) EXPECT() *MockTx_Expecter {
	return &MockTx_Expecter{mock: &_m.Mock}
}

// WithinTx provides a mock function for the type MockTx
func (_mock *MockTx) WithinTx(ctx context.Context, fn func(ctx context.Context) error) error {
	ret := _mock.Called(ctx, fn)

	if len(ret) == 0 {
		panic("no return value specified for WithinTx")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, func(ctx context.Context) error) error); ok {
		r0 = returnFunc(ctx, fn)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTx_WithinTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithinTx'
type MockTx_WithinTx_Call struct {
	*mock.Call
}

// WithinTx is a helper method to define mock.On call
//   - ctx context.Context
//   - fn func(ctx context.Context) error
func (_e *MockTx_Expecter) WithinTx(ctx interface{}, fn interface{}) *MockTx_WithinTx_Call {
	return &MockTx_WithinTx_Call{Call: _e.mock.On("WithinTx", ctx, fn)}
}

func (_c *MockTx_WithinTx_Call) Run(run func(ctx context.Context, fn func(ctx context.Context) error)) *MockTx_WithinTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 func(ctx context.Context) error
		if args[1] != nil {
			arg1 = args[1].(func(ctx context.Context) error)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTx_WithinTx_Call) Return(err error) *MockTx_WithinTx_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTx_WithinTx_Call) RunAndReturn(run func(ctx context.Context, fn func(ctx context.Context) error) error) *MockTx_WithinTx_Call {
	_c.Call.Return(run)
	return _c
}
